stages:
  - build
  - test

main build:
  stage: build
  only:
    - main
  image: maven:3.8.3-openjdk-17
  script:
    - mvn clean package
    - cp target/*.jar app.jar
  artifacts:
    paths:
      - app.jar

test build:
  stage: test
  only:
    - main
  image: maven:3.8.3-openjdk-17
  script:
    - java -jar app.jar &
    - sleep 20
    - curl --fail "http://localhost:8080/actuator/health"